[package]
org = "user"
name = "agri_backend"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.6.0"

[[dependency]]
org = "ballerina"
name = "jwt"
version = "2.15.0"

[[dependency]]
org = "ballerina"
name = "cache"
version = "3.10.0"
